### Signup
POST http://localhost:3000/auth/signup
content-Type: application/json

{
    "email":"test1@test.com",
    "password":"a"
} 

### Signin
POST http://localhost:3000/auth/signin
content-Type: application/json

{
    "email":"test1@test.com",
    "password":"a"
} 

### Find user
GET http://localhost:3000/auth/whoami


### Find a user with a particular id
GET http://localhost:3000/auth/3

### Find a user with a particular email id
GET http://localhost:3000/auth?email=a@gmail.com

### Delete a user with a particular id
DELETE http://localhost:3000/auth/2

### Update a user with a particular id
PATCH http://localhost:3000/auth/3
content-Type: application/json

{
    "email":"b@gmail.com",
    "password":"abcv"
} 